version: '3.2'

services:
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - 80:80
    links:
      - app-backend
      - app-frontend
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

  redis:
    container_name: 'redis'
    image: redis
    restart: always
    ports:
      - 6379:6379

  db:
    container_name: 'db'
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./config/mysql/init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

  app-backend:
    container_name: 'app-backend'
    image: node:18.13
    restart: always
    command: bash -c "npm i && npm run start:dev"
    working_dir: /app
    volumes:
      - ../app/backend:/app

  app-frontend:
    container_name: 'app-frontend'
    image: node:18.13
    restart: always
    command: bash -c "npm i && npm run start"
    working_dir: /app
    volumes:
      - ../app/frontend:/app
